### PR TITLE
Polish badge status in readme

### PR DESCRIPTION
**Pull request by Goooler**
[JDK19](https://github.com/mdogan/homebrew-zulu/actions/workflows/jdk17.yml)

https://github.com/mdogan/homebrew-zulu/actions/workflows/jdk17.yml/badge.svg?branch=master&event=push
https://github.com/mdogan/homebrew-zulu/actions/workflows/jdk17.yml

### CODE REVIEW

**Comment by mdogan** [comment]
Readme file is updated by `updater` app automatically. Can you please fix it, instead of manually editing readme file?

See https://github.com/mdogan/homebrew-zulu/blob/536bf7b7dea40198cba009e541abfe91efc2914a/updater/src/main/java/Main.java#L81-L111

**Comment by Goooler** [comment]
Yeah, I've also noticed that, will fix it later.

**Comment by Goooler** [comment]
Alright, updated. Please squash this PR.

**Comment by mdogan** [comment]
Merged by https://github.com/mdogan/homebrew-zulu/commit/a060f571f0cd3e62f8bdfe2b428d0d9803a602b9

**Pull request closed without merging**
